-- S500
SELECT ZAMESTNANEC.JMENO,
  ZAMESTNANEC.PRIJMENI,
  ZAMESTNANI.NAZEV_POZICE
FROM ZAMESTNANEC
LEFT JOIN PILOT
ON ZAMESTNANEC.ZAMESTNANEC_ID = PILOT.ZAMESTNANEC_ID
INNER JOIN ZAMESTNANI
ON ZAMESTNANI.ZAMESTNANI_ID = ZAMESTNANEC.ZAMESTNANI_ID
WHERE PILOT.PILOT_ID IS NULL;

-- S501:
SELECT tl.typ_letadla_id, tl.nazev, COUNT(l.letadlo_id) AS pocet_letadel
FROM AERO.typ_letadla tl LEFT JOIN AERO.letadlo l 
ON tl.typ_letadla_id = l.typ_letadla_id
GROUP BY tl.typ_letadla_id, tl.nazev
ORDER BY tl.typ_letadla_id;

-- S502:
SELECT z.prijmeni, z.jmeno, COUNT(l.cislo_letu) AS pocet_letu 
FROM AERO.let l RIGHT JOIN AERO.pilot p 
ON l.pilot_id = p.pilot_id, AERO.zamestnanec z
WHERE p.zamestnanec_id = z.zamestnanec_id
GROUP BY z.prijmeni, z.jmeno
ORDER BY z.prijmeni, z.jmeno;

-- S503
select typ_letadla.nazev,
  COUNT(LETADLO.LETADLO_ID) AS pocet_zakoupenych_letadel,
  TYP_LETADLA.POCET_MIST
FROM TYP_LETADLA
LEFT JOIN LETADLO
ON TYP_LETADLA.TYP_LETADLA_ID = LETADLO.TYP_LETADLA_ID
GROUP BY TYP_LETADLA.NAZEV,
  TYP_LETADLA.POCET_MIST
HAVING TYP_LETADLA.POCET_MIST > 100;

-- S504
SELECT TYP_LETADLA.NAZEV,
  COUNT(LETADLO.LETADLO_ID) AS pocet_zakoupenych_kusu
FROM TYP_LETADLA
LEFT JOIN LETADLO
ON TYP_LETADLA.TYP_LETADLA_ID = LETADLO.TYP_LETADLA_ID
GROUP BY TYP_LETADLA.NAZEV
HAVING COUNT(LETADLO.LETADLO_ID) = 0;

-- S505
SELECT DESTINACE.NAZEV
FROM ZASTAVKA
INNER JOIN LETOVA_LINKA
ON LETOVA_LINKA.CISLO_LETOVE_LINKY = ZASTAVKA.CISLO_LETOVE_LINKY
INNER JOIN LET
ON LETOVA_LINKA.CISLO_LETOVE_LINKY = LET.CISLO_LETOVE_LINKY
RIGHT JOIN DESTINACE
ON DESTINACE.DESTINACE_ID = ZASTAVKA.DESTINACE_ID
GROUP BY DESTINACE.NAZEV,
  LET.CISLO_LETU
HAVING LET.CISLO_LETU IS NULL
ORDER BY DESTINACE.NAZEV;

-- S506
SELECT TYP_LETADLA.NAZEV,
  LETADLO.LETADLO_ID
FROM LETADLO
INNER JOIN TYP_LETADLA
ON TYP_LETADLA.TYP_LETADLA_ID = LETADLO.TYP_LETADLA_ID
LEFT JOIN LET
ON LETADLO.LETADLO_ID = LET.LETADLO_ID
WHERE LET.CISLO_LETU IS NULL;

-- S507
SELECT ZAMESTNANEC.JMENO,
  ZAMESTNANEC.PRIJMENI
FROM PILOT
INNER JOIN ZAMESTNANEC
ON ZAMESTNANEC.ZAMESTNANEC_ID = PILOT.ZAMESTNANEC_ID
LEFT JOIN LET
ON PILOT.PILOT_ID     = LET.PILOT_ID
WHERE LET.CISLO_LETU IS NULL
GROUP BY 
  PILOT.PILOT_ID,
ZAMESTNANEC.JMENO,
  ZAMESTNANEC.PRIJMENI;
  
-- S508:
SELECT LET.CISLO_LETU,
  COUNT(UCASTNIK_LETU.PASAZER_ID) AS pocet_pasazeru,
  typ_letadla.pocet_mist,
  COUNT(UCASTNIK_LETU.PASAZER_ID) * 100 / TYP_LETADLA.POCET_MIST || '%' AS obsazenost,
  TYP_LETADLA.NAZEV
FROM LET
LEFT JOIN UCASTNIK_LETU
ON LET.CISLO_LETU = UCASTNIK_LETU.CISLO_LETU
LEFT JOIN LETADLO
ON LETADLO.LETADLO_ID = LET.LETADLO_ID
INNER JOIN TYP_LETADLA
ON TYP_LETADLA.TYP_LETADLA_ID = LETADLO.TYP_LETADLA_ID
GROUP BY LET.CISLO_LETU,
  TYP_LETADLA.POCET_MIST,
  TYP_LETADLA.NAZEV
ORDER BY COUNT(UCASTNIK_LETU.PASAZER_ID) * 100 / TYP_LETADLA.POCET_MIST DESC;

-- S509:
SELECT ZAMESTNANI.NAZEV_POZICE,
  COUNT(ZAMESTNANEC.ZAMESTNANEC_ID) AS pocet_zamestnancu
FROM ZAMESTNANI
LEFT JOIN ZAMESTNANEC
ON ZAMESTNANI.ZAMESTNANI_ID = ZAMESTNANEC.ZAMESTNANI_ID
GROUP BY ZAMESTNANI.NAZEV_POZICE
ORDER BY COUNT(ZAMESTNANEC.ZAMESTNANEC_ID) DESC;

